version: "3.1"

services:
  nginx:
    image: nginx
    container_name: my-nginx
    restart: always
    volumes:
      - ./www:/usr/share/nginx/html
      - ./conf.d:/etc/nginx/conf.d 
    ports:
      - "80:80"
    extra_hosts:
      - "dockerhost:192.168.1.7"  
